services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - blue-team-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - blue-team-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - blue-team-net

  wazuh:
    image: wazuh/wazuh-manager:4.9.0
    container_name: wazuh
    ports:
      - "55000:55000"
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
    volumes:
      - ./wazuh/config:/wazuh-config
      - wazuh_data:/var/ossec/data
    networks:
      - blue-team-net

  fleetdm:
    image: fleetdm/fleet:latest
    container_name: fleetdm
    ports:
      - "8080:8080"
    environment:
      - FLEET_SERVER_ADDRESS=0.0.0.0:8080
    networks:
      - blue-team-net

  thehive:
    image: thehiveproject/thehive:latest
    container_name: thehive
    depends_on:
      - elasticsearch
    ports:
      - "9000:9000"
    environment:
      - TH_SECRET=secret
      - TH_ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - thehive_data:/opt/thehive/data
    networks:
      - blue-team-net

  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    depends_on:
      - elasticsearch
    ports:
      - "9002:9001"
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
    volumes:
      - cortex_data:/opt/cortex/data
    networks:
      - blue-team-net

  zeek:
    image: blacktop/zeek:latest
    container_name: zeek
    volumes:
      - ./zeek/logs:/zeek/logs
    command: zeek -i eth0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    volumes:
      - ./suricata/logs:/var/log/suricata
    command: suricata -i eth0
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n/workflows:/home/node/.n8n
    networks:
      - blue-team-net

  kali:
    image: kalilinux/kali-rolling:latest
    container_name: kali
    volumes:
      - ./kali/logs:/var/log
    tty: true
    stdin_open: true
    networks:
      - attack-net
      - blue-team-net

  vuln-os:
    build:
      context: ./vuln-os/config
    container_name: vuln-os
    ports:
      - "8081:80"
      - "4450:445"
      - "22:22"
      - "21:21"
    networks:
      - attack-net
      - blue-team-net
    volumes:
      - ./vuln-os/logs:/var/log/vuln-os

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.0
    container_name: filebeat
    depends_on:
      - elasticsearch
      - logstash
    volumes:
      - ./filebeat/config:/usr/share/filebeat/config
      - ./zeek/logs:/zeek/logs:ro
      - ./suricata/logs:/suricata/logs:ro
      - ./kali/logs:/kali/logs:ro
      - ./vuln-os/logs:/vuln-os/logs:ro
    command: filebeat -e -c /usr/share/filebeat/config/filebeat.yml
    networks:
      - blue-team-net

volumes:
  es_data:
  wazuh_data:
  thehive_data:
  cortex_data:

networks:
  blue-team-net:
    driver: bridge
  attack-net:
    driver: bridge