version: '3.8'

services:
  kali:
    image: kalilinux/kali-rolling:latest
    container_name: kali
    privileged: true
    volumes:
      - kali_data:/root
    ports:
      - "2222:22"
      - "5901:5901"
    networks:
      - lab_network
    command: bash -c "apt-get update && apt-get install -y kali-linux-headless metasploit-framework openssh-server vnc4server && service ssh start && vncpasswd -f <<< 'password' > /root/.vnc/passwd && vnc4server :1 && tail -f /dev/null"

  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    volumes:
      - ./configs/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - suricata_logs:/var/log/suricata
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - elasticsearch
    command: suricata -c /etc/suricata/suricata.yaml -i eth0 --set logging.outputs.1.file.filename=/var/log/suricata/eve.json

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - lab_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.4
    container_name: logstash
    volumes:
      - suricata_logs:/var/log/suricata
    environment:
      - "LS_JAVA_OPTS=-Xms1g -Xmx1g"
    depends_on:
      - elasticsearch
    networks:
      - lab_network
    command: logstash -e 'input { file { path => "/var/log/suricata/eve.json" sincedb_path => "/dev/null" } } output { elasticsearch { hosts => ["elasticsearch:9200"] index => "suricata-%{+YYYY.MM.dd}" } }'

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - lab_network

  thehive:
    image: strangebee/thehive:latest
    container_name: thehive
    volumes:
      - ./configs/thehive/application.conf:/etc/thehive/application.conf
      - thehive_data:/opt/thehive/db
    ports:
      - "9000:9000"
    depends_on:
      - elasticsearch
    networks:
      - lab_network

  wazuh:
    image: wazuh/wazuh-manager:latest
    container_name: wazuh_manager
    volumes:
      - ./configs/wazuh/ossec.conf:/wazuh-config/ossec.conf
      - wazuh_data:/var/ossec/data
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "443:443"
    networks:
      - lab_network

  wazuh-agent:
    image: wazuh/wazuh-agent:latest
    container_name: wazuh_agent
    depends_on:
      - wazuh
    environment:
      - WAZUH_MANAGER=wazuh_manager
    networks:
      - lab_network

  caldera:
    image: mitre/caldera:latest
    container_name: caldera
    ports:
      - "8888:8888"
    volumes:
      - caldera_data:/opt/caldera
    networks:
      - lab_network

  metasploitable2:
    image: tleemcjr/metasploitable2:latest
    container_name: metasploitable2
    ports:
      - "8081:80"
      - "4451:445"
    networks:
      - lab_network

  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    ports:
      - "8082:80"
    networks:
      - lab_network

  winxp:
    image: vulnerables/windows-xp-ms08-067:latest
    container_name: winxp
    ports:
      - "4452:445"
      - "3389:3389"
    networks:
      - lab_network

  vuln-web:
    image: vulnerables/web-vuln:latest
    container_name: vuln_web
    ports:
      - "8083:80"
    networks:
      - lab_network

networks:
  lab_network:
    driver: bridge

volumes:
  kali_data:
  suricata_logs:
  es_data:
  thehive_data:
  wazuh_data:
  caldera_data:
