services:
  attacker:
    image: mitre/caldera:latest
    container_name: attacker
    networks: [blueteam_lab]
    ports: ['8888:8888']
  target:
    image: vulnerables/web-dvwa
    container_name: target
    networks: [blueteam_lab]
    ports: ['80:80']
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    networks: [blueteam_lab]
    cap_add: ['NET_ADMIN','NET_RAW']
    command: suricata -i eth0 -c /etc/suricata/suricata.yaml
    volumes:
      - ./suricata/logs:/var/log/suricata
  zeek:
    image: blacktop/zeek
    container_name: zeek
    networks: [blueteam_lab]
    cap_add: ['NET_ADMIN','NET_RAW']
    command: -i eth0
    volumes:
      - ./zeek/logs:/zeek/logs
  wazuh-manager:
    image: wazuh/wazuh:4.7.2
    container_name: wazuh-manager
    environment:
      - WAZUH_AGENT_GROUP=default
    networks: [blueteam_lab]
    ports: ['1514:1514/udp','55000:55000']
    volumes:
      - wazuh_data:/var/ossec
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: [blueteam_lab]
    volumes: [es_data:/usr/share/elasticsearch/data]
  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.0
    container_name: kibana
    networks: [blueteam_lab]
    ports: ['5601:5601']
    depends_on: [elasticsearch]
  wazuh-agent-target:
    image: wazuh/wazuh-agent:4.7.2
    container_name: wazuh-agent-target
    networks: [blueteam_lab]
    depends_on: [wazuh-manager]
    environment:
      - WAZUH_MANAGER_IP=wazuh-manager
  wazuh-agent-attacker:
    image: wazuh/wazuh-agent:4.7.2
    container_name: wazuh-agent-attacker
    networks: [blueteam_lab]
    depends_on: [wazuh-manager]
    environment:
      - WAZUH_MANAGER_IP=wazuh-manager

volumes:
  wazuh_data:
  es_data:
networks:
  blueteam_lab:
    driver: bridge
